### ISSUE TITLE
Custom unlockable unlocks gamestage, but doesn't trigger orestages update

### ISSUE THREAD

**Issue by codetaylor** [Coders-After-Dark/CompatSkills#10]
### What

1. Stage blocks using OreStages mod
2. Create Reskillable unlockable to unlock ore stage
3. Unlock Reskillable unlockable
4. Notice "You have unlocked..." message
5. Notice staged blocks aren't changed and no chunks are re-rendered

This happens in single player. Leaving the world and re-entering the world will display the staged blocks properly. Also, entering the command to add the stage does trigger the block change and the chunk update. Adding a different stage to the player does trigger the chunk update, but doesn't reveal the blocks.

Maybe the added stage isn't being synced to the client. I'm going to cross-post this in CompatSkills and GameStages. When `PlayerDataHandler.getStageData(player).unlockStage(gameStage)` is called, does GameStages sync the change with the client or is that the responsibility of the caller?

### Reference

* [GameStageUnlockable.java#L19](https://github.com/Coders-After-Dark/CompatSkills/blob/master/src/main/java/codersafterdark/compatskills/common/compats/gamestages/GameStageUnlockable.java#L19)

### Versions
Forge: 14.23.2.2618
Reskillable-1.12.2-1.0.0
CompatSkills-1.12.2-1.0.0
GameStages-1.12.2-1.0.85
OreStages-1.12.2-1.0.26

**Comment by Lanse505** [comment]
Fixing once I get home

**Comment by codetaylor** [comment]
Thanks @Lanse505 ! :)

**Comment by Lanse505** [comment]
This is fixed in-code

**Comment by Sixdd6** [comment]
So has the fix been pushed because I'm experiencing the same thing, the gamestage is unlocked according to chat but the chunk update never happens and the ores stay the same.

**Comment by Lanse505** [comment]
Its fixed but the update isnt public >.>
