### ISSUE TITLE
[Feature Request] Pam's Harvest Craft Support

### ISSUE THREAD

**Issue by Barerock** [Coders-After-Dark/CompatSkills#106]
With the addition of RLcraft to the brilliant mod packs that use this mod, I'd absolutely love to be able to use Pam's plants and foods with this mod. It's a great endeavor, so no rush, but I'm sure many people would appreciate the effort!

Loving the mod,
Thanks a ton!

**Comment by Lanse505** [comment]
https://github.com/Coders-After-Dark/CompatSkills/blob/master/CHANGELOG.MD#1100

We haven't had time to update the RTD yet, but we have Hunger and Saturation locking implemented.
