### ISSUE TITLE
Wings mod Compatibility

### ISSUE THREAD

**Issue by CLittleLunaC** [Coders-After-Dark/CompatSkills#113]
Hello I am working on a modpack that includes reskillable and its Compatibility addon and I wondering if Support for the wings mod by pau101 could be added? I want to add a requirement for the wings in order for the players to use them.

**Comment by pupnewfster** [comment]
Looking briefly at the mod's curseforge page I am guessing the wings are something you wear in an armor slot (or bauble slot)? If so just adding a requirement to them should make it so that they cannot be equipped effectively making it so players cannot use them without a given requirement.

**Comment by CLittleLunaC** [comment]
The wing can be equiped in either chest armor slot or the bauble chest equivalent. I added a requirement for the wings for the easier to obtain and lower durability wings they need to have agility lvl 12 and magic lvl 10.  And as of testing I am still able to equip them. I added the requirements before loading up the game since most config changes required a game restart

**Comment by pupnewfster** [comment]
No idea, I would need your latest.log and if you are doing it via compatskills your crafttweaker.log file.

**Comment by CLittleLunaC** [comment]
Alright I found the issue, I had a typo in the code. I really shouldn't be trusted with code XD
