### ISSUE TITLE
[Potential Feature] Compatibility with Tinker's Armoury

### ISSUE THREAD

**Issue by SansThePunster** [Coders-After-Dark/CompatSkills#116]
Compat skills adds Tinker's Construct, however, it would be nice to see its sister mod Tinker's Armoury added as well for a bit more content. Tinker's Armoury can be found here: https://www.curseforge.com/minecraft/mc-mods/constructs-armory

**Comment by pupnewfster** [comment]
Last I checked/used (like a year and a half ago now)... CompatSkills supported Construct's Armory just fine, so unless they have stopped using tinker's API and firing their events it should work fine.
