### ISSUE TITLE
 Could not get Skill_Change Tweaker to work

### ISSUE THREAD

**Issue by juraj-hrivnak** [Coders-After-Dark/CompatSkills#121]
> Using CompatSkills-1.12.2-1.17.0

- This is my script:

```
#modloaded compatskills reskillable
#priority 1001

mods.compatskills.GameStageUnlockable.addGameStageUnlockable("permMap", "map", 2, 2, "compatskills:mapping", 3);

mods.compatskills.SkillChange.addUnlockableUnlockCommands(<trait:compatskills:map>, "/give @e minecraft:stone 1");
```

- The /ct syntax is saying:
`Could not resolve <trait:compatskills:map>`

-  Priority is lower than for script that is creating the custom skill.
This is also happening after the game reloads.

The issue is that I don't know why.

**Comment by pupnewfster** [comment]
I think this is due to the docs being incorrect and it really being `<unlockable:compatskills:map>` not `<trait:compatskills:map>`

**Comment by juraj-hrivnak** [comment]
That was quick! Thanks! I will try it

**Comment by juraj-hrivnak** [comment]
Yes, it worked! Thanks! One question: Can you use @s (relative operator) in string commands?
