### ISSUE TITLE
Where to put resources for custom traits?

### ISSUE THREAD

**Issue by Sixdd6** [Coders-After-Dark/CompatSkills#13]
I have tried including my resources with resource loader but it did not work where I had them. What is the path that we should follow to put textures for custom traits?

**Comment by Lanse505** [comment]
Are we talking custom traits from a custom mod, or custom gamestage traits?

**Comment by Sixdd6** [comment]
sorry, custom gamestage traits.

**Comment by Lanse505** [comment]
Resources/assets/compatskills/textures/unlockables/name.png

**Comment by Lanse505** [comment]
Or smth like that

**Comment by Lanse505** [comment]
Omw home atm from requisitioning a phone for work

**Comment by Sixdd6** [comment]
ah, I was putting them under reskillable. Thanks again 👍 
No sweat, I'll let you know if it works.

**Comment by Lanse505** [comment]
Also for lang files its
Resources/assets/compatskills/lang/local.lang

**Comment by Lanse505** [comment]
Also a good reminder all files needs to be lowercased

**Comment by Sixdd6** [comment]
k

**Comment by Lanse505** [comment]
did it work?
