### ISSUE TITLE
Non-op players can't unlock gamestage traits

### ISSUE THREAD

**Issue by Sixdd6** [Coders-After-Dark/CompatSkills#15]
I've got a few people helping me test my modpack but when unlock a trait that gives a gamestage it tells them they don't have permission to use that command. I'm opped so it doesn't give this error when I do it. I checked the server log and it didn't output any kind of errors. Also of note is that traits worked fine before the latest update.

**Comment by Sixdd6** [comment]
No, that command is op only. I think the problem lies with the implementation of the fix for orestages. If I recall correctly the fix involves running the gamestage command in the background, maybe it isn't being run properly? I can confirm that the gamestage traits do unlock properly for ops, just not for regular players.

**Comment by Lanse505** [comment]
I've implemented a fix in-code.
I now fire the command from the server not from the player.

**Comment by Sixdd6** [comment]
sounds good, is this something I can test right away or do I need to wait for a release?

**Comment by Lanse505** [comment]
The current dev enviroment is a mess due to some things I'm doing for 1.2.0.
So currently no :/, you'd have to wait for a release, I'm sorry >-<

**Comment by Sixdd6** [comment]
no sweat, thank you for the fix :D
