### ISSUE TITLE
Invalid Level Lock

### ISSUE THREAD

**Issue by 8BrickDMG** [Coders-After-Dark/CompatSkills#22]
Hi guys,

I've added skill requirements through CompatSkills but I'm getting this error. I'm a bit confused as I tried a script I had done previously which loaded fine in previous builds.

Currently using the latest 1.2.1 versions of Reskillable and CompatSkills.

``[22:12:31] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] ERROR: [crafttweaker]: Error executing {[0:crafttweaker]: Reskillable.zs}: Invalid Level Lock for Input: reskillable:defense|16,reskillable:agility|16,reskillable:magic|16,adv|minecraft:end/find_end_city``

**Comment by SkySom** [comment]
"reskillable:defense|16","","",""
It's a set of strings, not a single one

**Comment by 8BrickDMG** [comment]
Oh right. Previously it was allowing it on one string.

Thanks for the help. Fixing it now.
