### ISSUE TITLE
Cannot use created skills

### ISSUE THREAD

**Issue by FireFlyerFighter** [Coders-After-Dark/CompatSkills#24]
I cannot use the skills created by using this mod with it.
If I create a skill, say "modid:test", I can't use it in a script to use it as a requirement.
By matter of fact, I can't use any skills created by a different mod than reskillable itself

**Comment by SkySom** [comment]
Can you show the script you are using to use these created skills?

**Comment by FireFlyerFighter** [comment]
`
mods.compatskills.SkillCreator.createNewSkill("woodenbridges:survival", "textures/blocks/ice_packed.png");
Requirement.addRequirement(<minecraft:apple>, "reskillable:farming|2", "woodenbridges:survival|2");`

**Comment by FireFlyerFighter** [comment]
I imported Requirement, just forgot to paste it in here
`import mods.compatskills.Requirement;`

**Comment by Lanse505** [comment]
Could you please gist your Crafttweaker.log file so we can see the actual error?

**Comment by FireFlyerFighter** [comment]
I "fixed".
I made the mistake to put "before:compatskills" in the dependencies for my mod which creates the skills, instead of "before:crafttweaker".
It also works now with skills created by compatskills, don't know what I have done wrong there.

All in all: sorry for wasting your time, I must have been more tired than I tought
