### ISSUE TITLE
Potential events to add locks for

### ISSUE THREAD

**Issue by pupnewfster** [Coders-After-Dark/CompatSkills#33]
- [x] `EntityMountEvent` Make it so player's cannot ride boats, horses, etc unless they meet the requirements for that vehicle.
- [ ] `AnvilRepairEvent` Make it so that a player cannot repair using an anvil unless they meet the requirements? Or maybe make it so that if they can't use the output they cannot create it.
- [x] `AnimalTameEvent`Similar to the first one. They must meet some requirements to be able to tame an animal.

**Comment by Lanse505** [comment]
So it's AnvilUpdateEvent, not AnvilRepairEvent.
Also, AnvilUpdateEvent doesn't have a player component we can reference.
