### ISSUE TITLE
Tcon Crash

### ISSUE THREAD

**Issue by Mattabase** [Coders-After-Dark/CompatSkills#60]
https://goo.gl/eeR1gu

**Comment by pupnewfster** [comment]
Update Reskillable given some of the features in the new CompatSkills version requires some of the API changes in the latest Reskillable version. I also had cleaned up the code a bit for Tinker's support as other parts of the CompatSkills update require the new API stuff.

**Comment by Mattabase** [comment]
Yeah sorry, this was user error. My bad.
