### ISSUE TITLE
[BUG] Skill Change Tweaker requires OP to run OP commands

### ISSUE THREAD

**Issue by Flytre** [Coders-After-Dark/CompatSkills#88]
I want to use the skill change tweaker to unlock game stages upon reaching a certain skill level. However, upon reaching the specified skill level, I get the error "You do not have permission to use this command."

**Comment by pupnewfster** [comment]
I will look into this when I get a chance I believe I know what line is the issue given I had left a comment to check if it would work. (It had seemed to work at the time but I forgot about the fact that I had op perms while testing op commands)

**Comment by Flytre** [comment]
How soon will this issue be fixed? It wouldn’t make sense for me to release my modpck until it is.

**Comment by pupnewfster** [comment]
This issue will probably be fixed either today or tomorrow, depending on when I get a chance to test my fix. When the next update with this included will be released I have no idea as I have been rather busy with courses and am working on adding/fixing a couple things to reskillable/compatskills

**Comment by pupnewfster** [comment]
Uploaded the fix to Curse. It will be available when they approve it.
