### ISSUE TITLE
[Feature Request] Robotic Parts Support

### ISSUE THREAD

**Issue by Deliphin** [Coders-After-Dark/CompatSkills#90]
I would like to be able to limit players from using certain cyberware from the [Robotic Parts](https://minecraft.curseforge.com/projects/roboticparts) mod and it's addon [ReWIRED](https://minecraft.curseforge.com/projects/rewired).

Basically, I want it so that players can't put the cyberware in the Robotic Surgeon until they have the correct levels to use it.

**Comment by pupnewfster** [comment]
I will look into it. At first glance I think this is probably relatively easily do-able given they actually have [cancellable events](https://github.com/An-Sar/Cyberware/blob/1.12/src/main/java/flaxbeard/cyberware/api/CyberwareSurgeryEvent.java). I just will need to look into what calls those events and how to get the current parts/attempted new parts.

**Comment by Deliphin** [comment]
Looking at the comments on the .java you linked, it seems to be for when players try to start surgery, rather than when they put them in the Robosurgeon. If you do it this way, I recommend adding some message popup (preferably configurable) telling the player they don't have the required skills to use it.
