### ISSUE TITLE
No way to hide/remove/modify buildin Reskilled traits using CompatSkill

### ISSUE THREAD

**Issue by Surac** [Coders-After-Dark/CompatSkills#91]
i seams i can create new Trais for Reskilled using Crafttweaker. But i cant accees the buildin Traits from Reskilled.
i have to disable a buildin Trait because it is unused in my modpack. Disable the Trait in Reskilled does not work, because the client still shows it as available and users can invest points to it.

**Comment by pupnewfster** [comment]
It is possible to disable built in traits using the trait bracket handler and setting enabled to false. I will leave this open however, as I think it makes sense to make CTUnlockable more like CTSkill is, and allow it to modify the config options of existing traits.

**Comment by Surac** [comment]
Can you please give an example code line for doing this using the bracket handler? i was unable to write a valid codeline to disable the hillwalker trait

**Comment by pupnewfster** [comment]
I believe `<trait:reskillable:hillwalker>.setEnabled(false);` should work. NOTE: This will work the same as just disabling it via the reskillable config. (In fact I think it will just change the config value for you if I remember correctly)
