### ISSUE TITLE
Crash with Blood Magic

### ISSUE THREAD

**Issue by Frinn38** [Coders-After-Dark/CompatSkills#98]
When activating a ritual after having disabled it by redstone, it make the game crash with a NullPointerException (because in that case the EntityPlayer is null).

Crash report : https://pastebin.com/rPYFcT3T

Step to reproduce : 
- Activate a ritual
- Power it via redstone (the ritual stop working)
- Disable the redstone signal (and then reboot your server)

**Comment by pupnewfster** [comment]
I uploaded a version that fixes this, and also makes sure none of the other events/compats crash if they get a null player. Once it is approved it should appear here: https://minecraft.curseforge.com/projects/compatskills/files/2677981 and sometime after that sync to the twitch client.

**Comment by Frinn38** [comment]
Thanks
